export interface KnowledgeItem {
  id: number;
  content: string;
}

export const knowledgeBase: KnowledgeItem[] = [
  // Existing fundamental knowledge

  // Comprehensive teaching-specific knowledge item for AI generation
  {
    id: 1,
    content: `A comprehensive lesson plan generated by the AI teaching assistant includes the following components to ensure effective teaching and student engagement:

1. Learning Objectives:
   - Clearly stated goals that define what students should know or be able to do by the end of the lesson.
   - Objectives should be specific, measurable, achievable, relevant, and time-bound (SMART).

2. Introduction (5-10 minutes):
   - An engaging opening that connects the lesson topic to real-life examples or prior knowledge.
   - Set the context and motivate students' interest.
   - Briefly outline what will be covered and the lesson’s purpose.

3. Main Content (20-30 minutes):
   - Clear, structured explanation of key concepts using simple language.
   - Use of visual aids such as diagrams, charts, or multimedia where appropriate.
   - Demonstrations or step-by-step walkthroughs to scaffold learning.
   - Integration of formative questions to check for understanding.

4. Interactive Activities (10-15 minutes):
   - Hands-on or group activities that encourage active participation and exploration.
   - Tasks could include experiments, problem-solving exercises, discussions, or role-plays.
   - Activities should reinforce the core content and stimulate critical thinking.

5. Practice Exercises (10 minutes):
   - Individual or group practice problems that consolidate learning.
   - A mix of question types ranging from recall to application and analysis.
   - Opportunities for students to receive timely feedback and clarifications.

6. Conclusion (5 minutes):
   - Summarization of the key points learned.
   - Address any remaining questions or misconceptions.
   - Provide homework or assignments for further practice and reflection.

7. Teaching Tips:
   - Adapt the pace according to student feedback during the lesson.
   - Use differentiated instruction to cater to diverse learners.
   - Foster a positive, inclusive classroom environment.
   - Continually assess understanding through questioning and formative assessments.

The AI assistant can customize lesson plans based on the grade level, subject, and specific topics, ensuring alignment with curriculum standards and student needs. It helps teachers save time by auto-generating structured, detailed, and pedagogically sound lesson resources.`
  }
];
